# Generated by Django 5.0.7 on 2025-05-02 00:10

import os
from django.db import migrations
from django.contrib.auth import get_user_model

def create_admin_user(apps, schema_editor):
    """Create a superuser from environment variables if they exist."""
    User = get_user_model()
    username = os.environ.get('SUPERUSER_USERNAME')
    email = os.environ.get('SUPERUSER_EMAIL')
    password = os.environ.get('SUPERUSER_PASSWORD')

    if username and email and password:
        # Check if the user already exists
        if not User.objects.filter(username=username).exists():
            print(f'\nCreating superuser: {username}')
            User.objects.create_superuser(username=username, email=email, password=password)
        else:
            print(f'\nSuperuser {username} already exists, skipping creation.')
    else:
        print('\nSuperuser environment variables (SUPERUSER_USERNAME, SUPERUSER_EMAIL, SUPERUSER_PASSWORD) not set, skipping superuser creation.')

class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'), # Make sure this dependency is correct for your project
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
