# Generated by Django 5.2 on 2025-05-08 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usser_id',
            new_name='user_id',
        ),
    ]
