# Generated by Django 5.2 on 2025-05-09 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('room_type', models.CharField(choices=[('TABLE', 'Table'), ('KARAOKE_ROOM', 'Karaoke Room')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_description', models.TextField(blank=True, null=True)),
                ('room_can_be_booked', models.BooleanField(default=True)),
                ('max_number_of_people', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('TABLE', 'Table'), ('KARAOKE_ROOM', 'Karaoke Room')], default='TABLE', max_length=20)),
            ],
        ),
    ]
