# Generated by Django 5.2 on 2025-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest_phone',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('TABLE', 'Table'), ('KARAOKE_ROOM', 'Karaoke Room')], default='TABLE', max_length=20),
        ),
    ]
