# Generated by Django 5.2 on 2025-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_guest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('TABLE', 'Table'), ('KARAOKE_ROOM', 'Karaoke Room')], default='TABLE', max_length=20),
        ),
    ]
