# Generated by Django 5.2 on 2025-05-08 16:03 (filename was 0003_auto_20250509_0003.py)

from django.db import migrations, connection

def create_initial_rooms(apps, schema_editor):
    Room = apps.get_model('reservations', 'Room') 
    db_alias = schema_editor.connection.alias

    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM reservations_room;")
        cursor.execute("ALTER TABLE reservations_room AUTO_INCREMENT = 1;")

    rooms_to_create = []

    rooms_to_create.append(
        Room(room_name="Karaoke Room 1", room_description="Main Karaoke Room", max_number_of_people=10, room_can_be_booked=True, room_type='KARAOKE_ROOM')
    )
    rooms_to_create.append(
        Room(room_name="Karaoke Room 2", room_description="Secondary Karaoke Room", max_number_of_people=6, room_can_be_booked=True, room_type='KARAOKE_ROOM')
    )

    for i in range(1, 11): 
        rooms_to_create.append(
            Room(room_name=f"Table {i}", room_description=f"Dining Table {i}", max_number_of_people=4, room_can_be_booked=True, room_type='TABLE')
        )

    Room.objects.using(db_alias).bulk_create(rooms_to_create)

def delete_initial_rooms(apps, schema_editor):
    Room = apps.get_model('reservations', 'Room')
    db_alias = schema_editor.connection.alias
    room_names_to_delete = ["Karaoke Room 1", "Karaoke Room 2"]
    for i in range(1, 11):
        room_names_to_delete.append(f"Table {i}")
    
    Room.objects.using(db_alias).filter(room_name__in=room_names_to_delete).delete()

    if not Room.objects.using(db_alias).exists():
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE reservations_room AUTO_INCREMENT = 1;")


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_room_room_type'), 
    ]

    operations = [
        migrations.RunPython(create_initial_rooms, reverse_code=delete_initial_rooms),
    ] 