# Generated by Django 5.2 on 2025-05-08 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_populate_initial_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('TABLE', 'Table'), ('KARAOKE_ROOM', 'Karaoke Room')], max_length=20),
        ),
    ]
