# Generated by Django 5.2 on 2025-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_duration_alter_reservation_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(default='no-email-provided@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
