# Generated by Django 5.2 on 2025-05-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='id',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='feedback_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
